### ISSUE TITLE
Test IoT-Lab RPI gateway code

### ISSUE THREAD

**Issue by pipex** [Inria-Chile/iot-lab-netboot#1]
A way to test [iot-lab-yocto](https://github.com/iot-lab/iot-lab-yocto) [Raspberry PI as gateway](https://github.com/iot-lab/iot-lab-yocto/pull/15) is necessary to ensure full compatibility with IoT-Lab gateway code. 

Please check this out @rdagher. I've left the compiled root files on the basecamp.

**Comment by rdagher** [comment]
I figured out a way of testing this by using one standalone M3 board as open node and no control node. Here are the steps, assuming that the gateway's IP address is `192.168.0.100`:

0. Launch the docker container (DHCP TFTP and NFS)
1. Prepare the image folders and configuration files
```bash
$ cd images/192.168.0.100/image
$ mkdir -p iotlab/users/test
$ sudo chown www-data:www-data iotlab/users/test
$ sudo chown www-data:www-data var/www
$ echo 'M3' > var/local/config/board_type
$ echo 'no' > var/local/config/contorl_node_type
$ echo 'm3-01' > var/local/config/hostname
```
2. Plug a FTDI to get access to the RPI serial console
3. Wait for the login to appear on the serial console
```bash
IoT-LAB Linux Welsh Edition 2017.03 m3-01 /dev/ttyS0

m3-01 login: 
```
4. Check that the port 8080 is open, which means that the gateway rest server started successfully
```bash
$ nmap 192.168.0.100

Starting Nmap 7.60 ( https://nmap.org ) at 2018-06-19 17:08 -04
Nmap scan report for 192.168.0.100
Host is up (0.0039s latency).
Not shown: 997 closed ports
PORT     STATE SERVICE
22/tcp   open  ssh
111/tcp  open  rpcbind
8080/tcp open  http-proxy

Nmap done: 1 IP address (1 host up) scanned in 0.12 seconds
```
5. Run a `status` request to see if open node is correctly detected
```bash
$ curl -X GET http://192.168.0.100:8080/status; echo
{"ret": 0}
```
6. Run a `blink autotest`request on the open node
```bash
curl -X PUT http://192.168.0.100:8080/autotest/blink; echo
{"mac": {"GWT": "b8:27:eb:d9:8b:80"}, "success": ["gw_mac_addr", "setup_cn_connection", "open_node_connection"], "ret": 2, "error": ["open_node_setup", "On Command: ['leds_off', '7']", "teardown"]}
```

It is important to note that if the step 1 is omitted, the gateway server will fail to start and the port '8080' will appear as closed in step 4.  Finally, one can use with any supported open node and/or control node by correctly setting up the board types in step 1.

**Comment by rdagher** [comment]
I wrote a setup script named [setup-image.sh](https://github.com/Inria-Chile/iot-lab-netboot/blob/develop/setup-image.sh) so one can setup the image prior to download on target gateway.
